artifact_root : artifacts

data_ingestion : 
  root_dir : artifacts/data_ingestion
  source_url : http://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  local_data_files : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion